### ISSUE TITLE
State authorities some text within tags discarded

### ISSUE THREAD

**Issue by mkorcy** [curationexperts/tufts-election#10]
I'm reporting this issue on behalf of one of our users, this can be reproduced by faceting on State -> Connecticut and scrolling down the bibliography section.

Comments from Erik:
"One issue I am noticing – anything in the StateAuthorities.xml file, from which the state information pulls – that is embedded in the xml tag <title> isn’t showing up at all.

So this line:

<li>Buell, Richard, Jr. and George J. Willauer. <title>Original Discontents: Commentaries on the Creation of Connecticut's Constitution of 1818.</title> Hamden, CT: The Acorn Club, 2007.</li>

Appears on the portal as this:

Buell, Richard, Jr. and George J. Willauer. Hamden, CT: The Acorn Club, 2007."

**Comment by val99erie** [comment]
@mkorcy  I wasn't able to see the exact problem with Connecticut because we don't have any Connecticut records in the spec fixtures, but I saw a similar problem with Alabama, where parts of the bibliography sections were missing.

There doesn't seem to be any problem with the parsing of the authority file -- I can see the full entries in memory in the rails console, and they look correct.  They just don't display properly.

The problem seems to be some bad HTML embedded in the authority file.  There are some ```<title>``` tags embedded inside the bibliography list.  I don't think ```<title>``` tags are allowed within an HTML body.  I suggest that we change all those ```<title>``` to ```<em>```.  I'll email you an updated authority file.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title

**Comment by val99erie** [comment]
@mkorcy  I'll assign the story back to you.  Please test with the updated file, and close the story if this solves the problem.

**Comment by mkorcy** [comment]
@val99erie erin tested this and confirmed its good to go, thanks.
